manga_analytics:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: manga_analytics
      threads: 4
      timeout_seconds: 300
      location: US
    docker:
      type: bigquery
      method: service-account
      keyfile: /secrets/gcp-key.json
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: manga_analytics
      threads: 4
      timeout_seconds: 300
      location: US
