name: Manga Analytics Pipeline

on:
  workflow_dispatch:
  push:
    paths:
      - "dbt/**"

jobs:
  dbt_run:
    name: Run dbt Models
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt-bigquery
        run: pip install dbt-bigquery

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"

      - name: dbt run staging
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        working-directory: dbt
        run: dbt run --select staging --profiles-dir .

      - name: dbt run marts
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        working-directory: dbt
        run: dbt run --select marts --profiles-dir .

      - name: dbt test
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        working-directory: dbt
        run: dbt test --profiles-dir .
